# Generated manually for Airish Fox style quiz stage 8.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("catalog", "0001_initial")]
    operations = [
        migrations.CreateModel(name="StyleQuizQuestion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=180, verbose_name="Вопрос")), ("slug", models.SlugField(unique=True, verbose_name="Slug")), ("help_text", models.CharField(blank=True, max_length=255, verbose_name="Подсказка")), ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")), ("is_active", models.BooleanField(default=True, verbose_name="Активен"))], options={"verbose_name":"Style quiz question","verbose_name_plural":"Style quiz questions","ordering":["sort_order","title"]}),
        migrations.CreateModel(name="StyleQuizSubmission", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("session_key", models.CharField(blank=True, max_length=80, verbose_name="Session key")), ("answers", models.JSONField(default=dict, verbose_name="Answers")), ("result_url", models.CharField(max_length=500, verbose_name="Result URL")), ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")), ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="style_quiz_submissions", to=settings.AUTH_USER_MODEL))], options={"verbose_name":"Style quiz submission","verbose_name_plural":"Style quiz submissions","ordering":["-created_at"]}),
        migrations.CreateModel(name="StyleQuizOption", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("label", models.CharField(max_length=140, verbose_name="Label")), ("value", models.CharField(max_length=80, verbose_name="Value")), ("preferred_color_hex", models.CharField(blank=True, max_length=7, verbose_name="Цвет")), ("gift_intent", models.BooleanField(default=False, verbose_name="Подарок")), ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")), ("is_active", models.BooleanField(default=True, verbose_name="Активен")), ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quiz_options", to="catalog.category", verbose_name="Категория")), ("mood", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quiz_options", to="catalog.moodcollection", verbose_name="Mood")), ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="style_quiz.stylequizquestion", verbose_name="Вопрос"))], options={"verbose_name":"Style quiz option","verbose_name_plural":"Style quiz options","ordering":["sort_order","label"]}),
    ]
