# Generated manually for Airish Fox limited drops stage 8.
import apps.catalog.services
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("catalog", "0001_initial")]
    operations = [
        migrations.CreateModel(name="ProductDrop", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160, verbose_name="Название")), ("slug", models.SlugField(unique=True, verbose_name="Slug")), ("description", models.TextField(blank=True, verbose_name="Описание")), ("hero_image", models.ImageField(blank=True, null=True, upload_to="drops/", validators=[apps.catalog.services.validate_image_extension, apps.catalog.services.validate_image_size], verbose_name="Hero image")), ("starts_at", models.DateTimeField(verbose_name="Начало")), ("ends_at", models.DateTimeField(verbose_name="Окончание")), ("is_active", models.BooleanField(default=True, verbose_name="Активен")), ("show_countdown", models.BooleanField(default=True, verbose_name="Показывать countdown")), ("waitlist_enabled", models.BooleanField(default=True, verbose_name="Waitlist")), ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO title")), ("seo_description", models.TextField(blank=True, verbose_name="SEO description")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("products", models.ManyToManyField(blank=True, related_name="drops", to="catalog.product"))], options={"verbose_name":"Product drop","verbose_name_plural":"Product drops","ordering":["-starts_at","name"]}),
        migrations.CreateModel(name="DropWaitlistEntry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("email", models.EmailField(max_length=254, verbose_name="Email")), ("name", models.CharField(blank=True, max_length=120, verbose_name="Имя")), ("created_at", models.DateTimeField(auto_now_add=True)), ("is_notified", models.BooleanField(default=False, verbose_name="Уведомлён")), ("drop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="waitlist_entries", to="drops.productdrop")), ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="drop_waitlist_entries", to=settings.AUTH_USER_MODEL))], options={"verbose_name":"Drop waitlist entry","verbose_name_plural":"Drop waitlist entries","ordering":["-created_at"], "constraints":[models.UniqueConstraint(fields=("drop", "email"), name="drops_unique_waitlist_email")]}),
    ]
