# Generated by Codex for production query hardening.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active"], name="catalog_product_active_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_new"], name="catalog_product_new_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_featured"], name="catalog_product_featured_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_fox_pick"], name="catalog_product_fox_pick_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["is_active"], name="catalog_variant_active_idx"),
        ),
    ]
