# Generated manually for Airish Fox brand experience stage 8.
import apps.catalog.services
import apps.brand.models
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="BrandFeatureToggle", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("key", models.SlugField(unique=True, verbose_name="Key")), ("name", models.CharField(max_length=140, verbose_name="Название")), ("description", models.TextField(blank=True, verbose_name="Описание")), ("is_enabled", models.BooleanField(default=True, verbose_name="Включено")), ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено"))], options={"verbose_name":"Brand feature toggle","verbose_name_plural":"Brand feature toggles","ordering":["key"]}),
        migrations.CreateModel(name="HomepageStoryBlock", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160, verbose_name="Заголовок")), ("subtitle", models.CharField(blank=True, max_length=180, verbose_name="Подзаголовок")), ("text", models.TextField(blank=True, verbose_name="Текст")), ("image", models.ImageField(blank=True, null=True, upload_to="brand/story/", validators=[apps.catalog.services.validate_image_extension, apps.catalog.services.validate_image_size], verbose_name="Изображение")), ("mascot_state", models.CharField(blank=True, default="happy", max_length=40, verbose_name="Mascot state")), ("cta_label", models.CharField(blank=True, max_length=80, verbose_name="CTA label")), ("cta_url", models.CharField(blank=True, max_length=240, verbose_name="CTA URL")), ("is_active", models.BooleanField(default=True, verbose_name="Активен")), ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок"))], options={"verbose_name":"Homepage story block","verbose_name_plural":"Homepage story blocks","ordering":["sort_order","title"]}),
        migrations.CreateModel(name="BrandBadge", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120, verbose_name="Название")), ("slug", models.SlugField(unique=True, verbose_name="Slug")), ("label", models.CharField(max_length=80, verbose_name="Label")), ("description", models.TextField(blank=True, verbose_name="Описание")), ("color_hex", models.CharField(default="#B8F2D0", max_length=7, validators=[apps.brand.models.color_hex_validator], verbose_name="Цвет")), ("icon_svg_name", models.CharField(blank=True, max_length=80, verbose_name="SVG icon name")), ("is_active", models.BooleanField(default=True, verbose_name="Активен")), ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок"))], options={"verbose_name":"Brand badge","verbose_name_plural":"Brand badges","ordering":["sort_order","name"]}),
    ]
